[package]
name = "simd"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
criterion = { version = "0.5.1" }
rand = { version = "0.8.5" }

[[bench]]
name = "loop"
harness = false

[[bench]]
name = "simd"
harness = false