[package]
name = "deflate"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3.26" }
thiserror = { version = "1.0.48" }
tokio = { version = "1.32.0", features = ["full"] }
