[package]
name = "huffman"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[rust]
debuginfo-level = 1

[dependencies]
byteorder = { version = "1.4.3" }
crc32fast = "1.3.2"
futures = { version = "0.3.28" }
thiserror = { version = "1.0.47" }
tokio = { version = "1.32.0", features = ["full"] }
