[package]
name = "wikipedia"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.12"
quick-xml = { version = "0.28.2" }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96" }
sevenz-rust = { version = "0.4.1" }
tokio = { version = "1.27.0", features = ["full"] }
