[package]
name = "simd"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1" }
packed_simd = { version = "0.3.8" }

[[bench]]
name = "simd"
harness = false

[[bench]]
name = "loop"
harness = false