[package]
name = "deflate"
version = "0.1.0"
edition = "2021"

[dependencies]
bitstream-io = { version = "1.7.0" }
byteorder = { version = "1.4.3" }
crc32fast = "1.3.2"
futures = { version = "0.3.28" }
thiserror = { version = "1.0.44" }
tokio = { version = "1.29.1", features = ["full"] }
