[package]
name = "sockets"
version = "0.1.0"
edition = "2021"

[dependencies]
testcontainers = { version = "0.14.0", features = ["tokio"] }
tokio = { version = "1.29.1", features = ["full"] }
tokio-postgres = { version = "0.7.8" }
