[package]
name = "jupyter-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { version = "0.21.0" }
bytes = { version = "1.4.0" }
chrono = { version = "0.4.24" }
fern = { version = "0.6.2" }
futures = { version = "0.3.28" }
hex = { version = "0.4.3" }
hmac-sha256 = { version = "1.1.6" }
http-types = "2.12.0"
log = { version = "0.4.17" }
maplit = "1.0.2"
serde = { version = "1.0.159" }
serde_json = { version = "1.0.96" }
structopt = { version = "0.3.26" }
surf = { version = "2.3.2" }
thiserror = { version = "1.0.40" }
tokio = { version = "1.27.0", features = ["full"] }
uuid = { version = "1.3.1", features = ["v4"] }
zeromq = { version = "0.3.3", features = ["all-transport"] }
