[package]
name = "rle"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { version = "1.4.3" }
futures = { version = "0.3.28" }
thiserror = { version = "1.0.44" }
tokio = { version = "1.29.1", features = ["full"] }
