[build]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
]

[alias]
run-demo = "run --target x86_64-unknown-none -p demo"
test-io = "test --lib --target x86_64-unknown-linux-gnu --package adma-io"
test-trace = "test --lib --target x86_64-unknown-linux-gnu --package adma-trace --features tracing"
