[build]
rustflags = []

[target.x86_64-unknown-none]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
]

[alias]
run-demo = "run --target x86_64-unknown-none -p demo --features io-tracing"
build-all = "build --lib --target x86_64-unknown-linux-gnu"
test-all = "test --lib --target x86_64-unknown-linux-gnu -- --test-threads=1"
test-heap = "test --lib --target x86_64-unknown-linux-gnu --package adma-heap -- --test-threads=1"
test-io = "test --lib --target x86_64-unknown-linux-gnu --package adma-io -- --test-threads=1"
test-trace = "test --lib --target x86_64-unknown-linux-gnu --package adma-trace -- --test-threads=1"
test-uring = "test --lib --target x86_64-unknown-linux-gnu --package adma-uring -- --test-threads=1"
cover-io = "tarpaulin --lib --target x86_64-unknown-linux-gnu --package adma-io --out html"
